In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
import datetime as dt
df=pd.read_excel('Dataset.xlsx',names=['observation_date','gold'])
df=df.iloc[10:]
new_df=df
df['observation_date']=pd.to_datetime(df['observation_date'])
df.head()

observation_date  gold
10       1968-04-01    38
11       1968-04-02  37.6
12       1968-04-03  37.7
13       1968-04-04  36.7
14       1968-04-05  37.2

In [3]:
import datetime as dt

In [4]:
df['observation_date']=df['observation_date'].map(dt.datetime.toordinal)

In [5]:
df.head()

observation_date  gold
10            718523    38
11            718524  37.6
12            718525  37.7
13            718526  36.7
14            718527  37.2

In [6]:
df.isnull().sum()

observation_date      0
gold                431
dtype: int64

In [7]:
df=df.fillna(method='pad')

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model=LinearRegression()

In [10]:
x=df.drop(columns=['gold'])
#x=pd.to_numeric(x)
y=df['gold']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [13]:
xtrain.shape

(11126, 1)

In [61]:
xtest.head(15)

observation_date
8951             731040
3109             722860
9839             732282
1121             720078
11797            735024
9168             731343
1502             720611
514              719227
8547             730474
76               718615
12339            735782
8699             730686
11147            734114
13085            736828
5671             726448

In [15]:
model.fit(xtrain,ytrain)

LinearRegression()

In [47]:
ypred=model.predict([[722860]])

In [48]:
ypred

array([186.57829199])

In [18]:
import pickle

In [19]:
pickle.dump(model,open('linear_pkl.pkl','wb'))

In [20]:
mod=pickle.load(open('linear_pkl.pkl','rb'))

In [37]:
mod.predict([[724664]])

array([-123.30408509])

In [22]:
# df['observation_date']=df['observation_date'].map(dt.datetime.toordinal)

In [23]:
import datetime
ds=(input(datetime.date))

<class 'datetime.date'>2015-09-09


In [ ]:
# d=datetime.date(year=2010, month=3, day=1)
# d.toordinal()

In [ ]:
1980-02-13


In [63]:
year=int(input())
month=int(input())
day=int(input())
k=datetime.date(year,month,day)
k=k.toordinal()
mod.predict([[k]])

1989
12
08


array([442.65817196])